#!/usr/bin/env bash
set \
    -o errexit \
    -o nounset

if ! test -v SNAP_ARCH_TRIPLET; then
    printf -- \
        '%s: Error: This launcher requires SNAP_ARCH_TRIPLET environmental variable to be set an exported.\n' \
        "$(basename "${BASH_SOURCE[0]}")" \
        1>&2
    exit 1
fi

export \
    LD_LIBRARY_PATH="${SNAP}"/usr/lib/"${SNAP_ARCH_TRIPLET}"/gvfs:"${LD_LIBRARY_PATH}"

exec "${@}"
